### ISSUE TITLE
Race condition in relations that prevents working cluster.

### ISSUE THREAD

**Issue by dmzoneill** [Juniper/contrail-charms#111]
There is a race condition in the relation between contrail-keystone-auth and contrail controller, that leaves the cluster in broken state.

It's impossible to do a automated installation of the cluster without running into a broken state in either of 2 broken data relations

'auth-info' or 'cloud_orchstrator'.

Manuall install works as expected, waiting for the charms to complete before adding the subsequent charms and applying relations.

**e.g of broken state** 

```
contrail-analytics/0       blocked      idle       5        10.5.0.26                                   Missing cloud_orchestrator info in relation with contrail-controller.
contrail-analytics/1       blocked      idle       6        10.5.0.9                                    Missing cloud_orchestrator info in relation with contrail-controller.
contrail-analytics/2*      blocked      idle       7        10.5.0.29                                   Missing cloud_orchestrator info in relation with contrail-controller.
contrail-analyticsdb/0*    blocked      idle       9        10.5.0.8                                    Missing cloud_orchestrator info in relation with contrail-controller.
contrail-analyticsdb/1     blocked      idle       10       10.5.0.10                                   Missing cloud_orchestrator info in relation with contrail-controller.
contrail-analyticsdb/2     blocked      idle       11       10.5.0.23                                   Missing cloud_orchestrator info in relation with contrail-controller.
contrail-controller/3      blocked      executing  1        10.5.0.12       8080/tcp,8082/tcp,8143/tcp  Missing cloud orchestrator info in relations.
contrail-controller/5*     blocked      idle       3        10.5.0.17       8080/tcp,8082/tcp,8143/tcp  Missing relations: contrail-cluster
contrail-controller/6      error        idle       14       10.5.0.36       8080/tcp,8082/tcp,8143/tcp  hook failed: "contrail-analytics-relation-joined"
contrail-keystone-auth/1*  active       executing  1        10.5.0.12                                   Unit is ready
```

**Bundle**
```
ubuntu@dmzoneill-bastion:~/openstack-base$ cat bundle-ctl.yaml 
machines:
  '0':
    series: bionic
  '1':
    series: bionic
  '2':
    series: bionic
  '3':
    series: bionic
  '4':
    series: bionic
  '5':
    series: bionic
  '6':
    series: bionic
  '7':
    series: bionic
  '8':
    series: bionic
  '9':
    series: bionic
    constraints: cores=2 mem=6G
  '10':
    series: bionic
    constraints: cores=2 mem=6G
  '11':
    series: bionic
    constraints: cores=2 mem=6G
relations:
- - nova-compute:amqp
  - rabbitmq-server:amqp
- - neutron-gateway:amqp
  - rabbitmq-server:amqp
- - keystone:shared-db
  - mysql:shared-db
- - nova-cloud-controller:identity-service
  - keystone:identity-service
- - glance:identity-service
  - keystone:identity-service
- - neutron-api:identity-service
  - keystone:identity-service
- - neutron-openvswitch:neutron-plugin-api
  - neutron-api:neutron-plugin-api
- - neutron-api:shared-db
  - mysql:shared-db
- - neutron-api:amqp
  - rabbitmq-server:amqp
- - neutron-gateway:neutron-plugin-api
  - neutron-api:neutron-plugin-api
- - glance:shared-db
  - mysql:shared-db
- - glance:amqp
  - rabbitmq-server:amqp
- - nova-cloud-controller:image-service
  - glance:image-service
- - nova-compute:image-service
  - glance:image-service
- - nova-cloud-controller:cloud-compute
  - nova-compute:cloud-compute
- - nova-cloud-controller:amqp
  - rabbitmq-server:amqp
- - nova-cloud-controller:quantum-network-service
  - neutron-gateway:quantum-network-service
- - nova-compute:neutron-plugin
  - neutron-openvswitch:neutron-plugin
- - neutron-openvswitch:amqp
  - rabbitmq-server:amqp
- - openstack-dashboard:identity-service
  - keystone:identity-service
- - openstack-dashboard:shared-db
  - mysql:shared-db
- - nova-cloud-controller:shared-db
  - mysql:shared-db
- - nova-cloud-controller:neutron-api
  - neutron-api:neutron-api
- - cinder:image-service
  - glance:image-service
- - cinder:amqp
  - rabbitmq-server:amqp
- - cinder:identity-service
  - keystone:identity-service
- - cinder:cinder-volume-service
  - nova-cloud-controller:cinder-volume-service
- - cinder-ceph:storage-backend
  - cinder:storage-backend
- - ceph-mon:client
  - nova-compute:ceph
- - nova-compute:ceph-access
  - cinder-ceph:ceph-access
- - cinder:shared-db
  - mysql:shared-db
- - ceph-mon:client
  - cinder-ceph:ceph
- - ceph-mon:client
  - glance:ceph
- - ceph-osd:mon
  - ceph-mon:osd
- - ntp:juju-info
  - nova-compute:juju-info
- - ntp:juju-info
  - neutron-gateway:juju-info
- - ceph-radosgw:mon
  - ceph-mon:radosgw
- - ceph-radosgw:identity-service
  - keystone:identity-service
- - contrail-analyticsdb:contrail-analyticsdb
  - contrail-analytics:contrail-analyticsdb
- - contrail-analyticsdb:contrail-analyticsdb
  - contrail-controller:contrail-analyticsdb
- - contrail-controller:contrail-controller
  - contrail-agent:contrail-controller
- - contrail-controller:contrail-controller
  - contrail-openstack:contrail-controller
- - contrail-analytics:contrail-analytics
  - contrail-controller:contrail-analytics
- - contrail-openstack:neutron-api
  - neutron-api:neutron-plugin-api-subordinate
- - contrail-openstack:nova-compute
  - nova-compute:neutron-plugin
- - contrail-agent:juju-info
  - nova-compute:juju-info
- - contrail-keystone-auth:contrail-auth
  - contrail-controller:contrail-auth
- - keystone:identity-admin
  - contrail-keystone-auth:identity-admin
series: bionic
services:
  ceph-mon:
    annotations:
      gui-x: '750'
      gui-y: '500'
    bindings:
      ? ''
    charm: cs:ceph-mon
    num_units: 3
    options:
      expected-osd-count: 3
      monitor-count: 3
      source: cloud:bionic-stein
    to:
    - '1'
    - '2'
    - '3'
  ceph-osd:
    annotations:
      gui-x: '1000'
      gui-y: '500'
    bindings:
      ? ''
    charm: cs:ceph-osd
    num_units: 3
    options:
      osd-devices: /dev/sdb /dev/vdb
      source: cloud:bionic-stein
    to:
    - '1'
    - '2'
    - '3'
  ceph-radosgw:
    annotations:
      gui-x: '1000'
      gui-y: '250'
    bindings:
      ? ''
    charm: cs:ceph-radosgw
    num_units: 1
    options:
      source: cloud:bionic-stein
  cinder:
    annotations:
      gui-x: '750'
      gui-y: '0'
    bindings:
      ? ''
    charm: cs:cinder
    num_units: 1
    options:
      block-device: None
      glance-api-version: 2
      openstack-origin: cloud:bionic-stein
      worker-multiplier: 0.25
    to:
    - '4'
  cinder-ceph:
    annotations:
      gui-x: '750'
      gui-y: '250'
    charm: cs:cinder-ceph
    num_units: 0
  glance:
    annotations:
      gui-x: '250'
      gui-y: '0'
    bindings:
      ? ''
    charm: cs:glance
    num_units: 1
    options:
      openstack-origin: cloud:bionic-stein
      worker-multiplier: 0.25
    to:
    - '5'
  keystone:
    annotations:
      gui-x: '500'
      gui-y: '0'
    bindings:
      ? ''
    charm: cs:keystone
    num_units: 1
    options:
      openstack-origin: cloud:bionic-stein
      worker-multiplier: 0.25
    to:
    - '6'
  mysql:
    annotations:
      gui-x: '0'
      gui-y: '250'
    bindings:
      ? ''
    charm: cs:percona-cluster
    num_units: 1
    options:
      innodb-buffer-pool-size: 256M
      max-connections: 1000
      performance-schema: true
    to:
    - '7'
  neutron-api:
    annotations:
      gui-x: '500'
      gui-y: '500'
    bindings:
      ? ''
    charm: cs:neutron-api
    num_units: 1
    options:
      flat-network-providers: physnet1
      neutron-security-groups: true
      openstack-origin: cloud:bionic-stein
      worker-multiplier: 0.25
    to:
    - '8'
  neutron-gateway:
    annotations:
      gui-x: '0'
      gui-y: '0'
    bindings:
      ? ''
    charm: cs:neutron-gateway
    num_units: 1
    options:
      bridge-mappings: physnet1:br-ex
      data-port: br-ex:eno2
      openstack-origin: cloud:bionic-stein
      worker-multiplier: 0.25
    to:
    - '0'
  neutron-openvswitch:
    annotations:
      gui-x: '250'
      gui-y: '500'
    charm: cs:neutron-openvswitch
    num_units: 0
  nova-cloud-controller:
    annotations:
      gui-x: '0'
      gui-y: '500'
    bindings:
      ? ''
    charm: cs:nova-cloud-controller
    num_units: 1
    options:
      network-manager: Neutron
      openstack-origin: cloud:bionic-stein
      worker-multiplier: 0.25
    to:
    - '9'
  nova-compute:
    annotations:
      gui-x: '250'
      gui-y: '250'
    bindings:
      ? ''
    charm: cs:nova-compute
    num_units: 1
    options:
      config-flags: default_ephemeral_format=ext4
      enable-live-migration: true
      enable-resize: true
      migration-auth-type: ssh
      openstack-origin: cloud:bionic-stein
    to:
    - '1'
  ntp:
    annotations:
      gui-x: '1000'
      gui-y: '0'
    charm: cs:ntp
    num_units: 0
  openstack-dashboard:
    annotations:
      gui-x: '500'
      gui-y: '-250'
    bindings:
      ? ''
    charm: cs:openstack-dashboard
    num_units: 1
    options:
      openstack-origin: cloud:bionic-stein
    to:
    - '10'
  rabbitmq-server:
    annotations:
      gui-x: '500'
      gui-y: '250'
    bindings:
      ? ''
    charm: cs:rabbitmq-server
    num_units: 1
    to:
    - '11'
  contrail-agent:
    charm: cs:~juniper-os-software/contrail-agent
    num_units: 0
    options:
      image-tag: 5.0.2-0.360-queens
      docker-password: ................
      docker-registry: hub.juniper.net/contrail
      docker-user: .............
  contrail-openstack:
    charm: cs:~juniper-os-software/contrail-openstack
    num_units: 0
    options:
      image-tag: 5.0.2-0.360-queens
      docker-password: .............................
      docker-registry: hub.juniper.net/contrail
      docker-user: .........................
  contrail-controller:
    charm: cs:~juniper-os-software/contrail-controller
    num_units: 3
    options:
      auth-mode: no-auth
      cassandra-minimum-diskgb: "4"
      image-tag: 5.0.2-0.360-queens
      docker-password: .......................
      docker-registry: hub.juniper.net/contrail
      docker-user: .........................
    to:
    - '1'
    - '2'
    - '3'
  contrail-analytics:
    charm: cs:~juniper-os-software/contrail-analytics
    num_units: 3
    options:
      image-tag: 5.0.2-0.360-queens
      docker-password: .................
      docker-registry: hub.juniper.net/contrail
      docker-user: .................
    to:
    - '5'
    - '6'
    - '7'
  contrail-analyticsdb:
    charm: cs:~juniper-os-software/contrail-analyticsdb
    num_units: 3
    options:
      image-tag: 5.0.2-0.360-queens
      docker-password: ....................
      docker-registry: hub.juniper.net/contrail
      docker-user: .....................
      cassandra-jvm-extra-opts: "-Xms4096m -Xmx4096m"
      cassandra-minimum-diskgb: "4"
    to:
    - '9'
    - '10'
    - '11'
  contrail-keystone-auth:
    charm: cs:~juniper-os-software/contrail-keystone-auth
    num_units: 1
    to:
    - '1'
  openstack-dashboard:
    annotations:
      gui-x: '500'
      gui-y: '-250'
    bindings:
      ? ''
    charm: cs:openstack-dashboard
    num_units: 1
    options:
      openstack-origin: cloud:bionic-stein
  rabbitmq-server:
    annotations:
      gui-x: '500'
      gui-y: '250'
    bindings:
      ? ''
    charm: cs:rabbitmq-server
    num_units: 1
variables:
  data-port: br-ex:eno2
  expected-mon-count: 3
  expected-osd-count: 3
  mysql-connections: 1000
  openstack-origin: cloud:bionic-stein
  osd-devices: /dev/sdb /dev/vdb
  worker-multiplier: 0.25
```

**full juju status**
```
ubuntu@dmzoneill-bastion:~/openstack-base$ juju status 
Model    Controller               Cloud/Region             Version  SLA          Timestamp
default  serverstack-serverstack  serverstack/serverstack  2.6.6    unsupported  14:38:44Z

App                     Version       Status       Scale  Charm                   Store       Rev  OS      Notes
ceph-mon                13.2.6        error            3  ceph-mon                jujucharms   42  ubuntu  
ceph-osd                13.2.6        maintenance      3  ceph-osd                jujucharms  291  ubuntu  
ceph-radosgw            13.2.6        blocked          1  ceph-radosgw            jujucharms  281  ubuntu  
cinder                  14.0.0        active           1  cinder                  jujucharms  290  ubuntu  
cinder-ceph             14.0.0        active           1  cinder-ceph             jujucharms  249  ubuntu  
contrail-agent                        waiting          1  contrail-agent          jujucharms    7  ubuntu  
contrail-analytics                    blocked          3  contrail-analytics      jujucharms    6  ubuntu  
contrail-analyticsdb                  blocked          3  contrail-analyticsdb    jujucharms    6  ubuntu  
contrail-controller                   error            3  contrail-controller     jujucharms    6  ubuntu  
contrail-keystone-auth                active           1  contrail-keystone-auth  jujucharms    6  ubuntu  
contrail-openstack      5.0-360.el7   active         1/2  contrail-openstack      jujucharms    6  ubuntu  
glance                  18.0.0        active           1  glance                  jujucharms  287  ubuntu  
keystone                15.0.0        active           1  keystone                jujucharms  306  ubuntu  
mysql                   5.7.20-29.24  active           1  percona-cluster         jujucharms  279  ubuntu  
neutron-api             14.0.2        active           1  neutron-api             jujucharms  277  ubuntu  
neutron-gateway         14.0.2        active           1  neutron-gateway         jujucharms  273  ubuntu  
neutron-openvswitch     14.0.2        active           1  neutron-openvswitch     jujucharms  267  ubuntu  
nova-cloud-controller   19.0.1        active           1  nova-cloud-controller   jujucharms  332  ubuntu  
nova-compute            19.0.1        active           1  nova-compute            jujucharms  307  ubuntu  
ntp                     3.2           active           2  ntp                     jujucharms   35  ubuntu  
openstack-dashboard     15.0.0        active           1  openstack-dashboard     jujucharms  293  ubuntu  
rabbitmq-server         3.6.10        active           1  rabbitmq-server         jujucharms   94  ubuntu  

Unit                       Workload     Agent      Machine  Public address  Ports                       Message
ceph-mon/0                 error        idle       1        10.5.0.12                                   hook failed: "leader-settings-changed"
ceph-mon/2*                blocked      idle       3        10.5.0.17                                   Unit not clustered (no quorum)
ceph-mon/3                 blocked      idle       14       10.5.0.36                                   Unit not clustered (no quorum)
ceph-osd/0                 active       executing  1        10.5.0.12                                   Unit is ready (1 OSD)
ceph-osd/2*                active       idle       3        10.5.0.17                                   Unit is ready (1 OSD)
ceph-osd/3                 maintenance  executing  14       10.5.0.36                                   (config-changed) Initializing device /dev/vdb
ceph-radosgw/0*            blocked      idle       0        10.5.0.4        80/tcp                      Missing relations: mon
cinder/0*                  active       idle       4        10.5.0.6        8776/tcp                    Unit is ready
  cinder-ceph/0*           active       idle                10.5.0.6                                    Unit is ready
contrail-analytics/0       blocked      idle       5        10.5.0.26                                   Missing cloud_orchestrator info in relation with contrail-controller.
contrail-analytics/1       blocked      idle       6        10.5.0.9                                    Missing cloud_orchestrator info in relation with contrail-controller.
contrail-analytics/2*      blocked      idle       7        10.5.0.29                                   Missing cloud_orchestrator info in relation with contrail-controller.
contrail-analyticsdb/0*    blocked      idle       9        10.5.0.8                                    Missing cloud_orchestrator info in relation with contrail-controller.
contrail-analyticsdb/1     blocked      idle       10       10.5.0.10                                   Missing cloud_orchestrator info in relation with contrail-controller.
contrail-analyticsdb/2     blocked      idle       11       10.5.0.23                                   Missing cloud_orchestrator info in relation with contrail-controller.
contrail-controller/3      blocked      executing  1        10.5.0.12       8080/tcp,8082/tcp,8143/tcp  Missing cloud orchestrator info in relations.
contrail-controller/5*     blocked      idle       3        10.5.0.17       8080/tcp,8082/tcp,8143/tcp  Missing relations: contrail-cluster
contrail-controller/6      error        idle       14       10.5.0.36       8080/tcp,8082/tcp,8143/tcp  hook failed: "contrail-analytics-relation-joined"
contrail-keystone-auth/1*  active       executing  1        10.5.0.12                                   Unit is ready
glance/0*                  active       idle       5        10.5.0.26       9292/tcp                    Unit is ready
keystone/0*                active       idle       6        10.5.0.9        5000/tcp                    Unit is ready
mysql/0*                   active       idle       7        10.5.0.29       3306/tcp                    Unit is ready
neutron-api/0*             active       idle       8        10.5.0.3        9696/tcp                    Unit is ready
  contrail-openstack/0*    active       idle                10.5.0.3                                    Unit is ready
neutron-gateway/0*         active       idle       0        10.5.0.4                                    Unit is ready
  ntp/0*                   active       idle                10.5.0.4        123/udp                     chrony: Ready
nova-cloud-controller/0*   active       idle       9        10.5.0.8        8774/tcp,8775/tcp,8778/tcp  Unit is ready
nova-compute/0*            active       idle       1        10.5.0.12                                   Unit is ready
  contrail-agent/0*        waiting      idle                10.5.0.12                                   agent is not ready. Reason: initializing
  contrail-openstack/1     unknown      lost                10.5.0.12                                   agent lost, see 'juju show-status-log contrail-openstack/1'
  neutron-openvswitch/0*   active       idle                10.5.0.12                                   Unit is ready
  ntp/1                    active       executing           10.5.0.12       123/udp                     (leader-settings-changed) chrony: Ready
openstack-dashboard/0*     active       idle       12       10.5.0.27       80/tcp,443/tcp              Unit is ready
rabbitmq-server/0*         active       idle       13       10.5.0.20       5672/tcp                    Unit is ready

Machine  State    DNS        Inst id                               Series  AZ    Message
0        started  10.5.0.4   b8f4bfa3-7180-49d2-abcd-c1b79778af09  bionic  nova  ACTIVE
1        started  10.5.0.12  e87b5c6f-556d-432c-9b0c-aa11aecc31bc  bionic  nova  ACTIVE
3        started  10.5.0.17  2da47cac-9285-486f-81eb-2f1c3c52ba5b  bionic  nova  ACTIVE
4        started  10.5.0.6   ce8153dd-760b-46bf-984b-9b23c2d2e24a  bionic  nova  ACTIVE
5        started  10.5.0.26  21d6ceb4-0d8e-4b7f-8f89-7f8d7f96b737  bionic  nova  ACTIVE
6        started  10.5.0.9   abb866e9-6d9c-47dd-b3d3-bde08108e2d8  bionic  nova  ACTIVE
7        started  10.5.0.29  818dcb33-040c-41ae-b47c-109fdfe085d9  bionic  nova  ACTIVE
8        started  10.5.0.3   d28b8b40-7efd-4e53-bfaf-9f8bc0964eb4  bionic  nova  ACTIVE
9        started  10.5.0.8   0be41591-e13a-4815-b25e-fe52a337461a  bionic  nova  ACTIVE
10       started  10.5.0.10  e30369ff-6a03-4147-b377-52a2a3d1627f  bionic  nova  ACTIVE
11       started  10.5.0.23  b8a6d493-b92b-45ba-b895-25157b9b2571  bionic  nova  ACTIVE
12       started  10.5.0.27  dd95dae2-36d9-4121-b7e9-f085be8ad52f  bionic  nova  ACTIVE
13       started  10.5.0.20  27bf7e10-338e-428f-9128-5ebd5de62f8a  bionic  nova  ACTIVE
14       started  10.5.0.36  ab044c22-5fd5-47a2-9c96-10676ee69507  bionic  nova  ACTIVE
```
